Add glyph lookup support
go-text/font pull request #3
Opened 2021-12-07 19:09 UTC by benoitkugler

Implementing https://github.com/go-text/shaping/issues/8 requires to know the runes supported by a font.
I then propose to add the NominalGlyph method (which is usually implemented by looking in the cmap table).

2021-12-08 01:32 UTC, andydotxyz requested changes
Can we do this without adding an external dependency?

2021-12-08 13:25 UTC, benoitkugler commented
> Can we do this without adding an external dependency?

So far, the shaper expects that `go-text/font.Font` objects are actually `textlayout/fonts.Face`. So, to keep interfaces assignables, we have to keep the same methods signatures. 

From what I understand, the go-text/font package is meant to implement the fundamental font file reading logic. But, until we make progress on this front, we have to rely on `textlayout/fonts` (which is in-fact a first version of what go-text/font should become).

It's true that we will have to keep a dependency to `textlayout` until we merge it into go-text. But again, a font library is needed as a backbone for text shaping, so the two modules (font and shaping) are tightly coupled (as an evidence, consider that Harfbuzz actually mixes font file parsing and text shaping in the same project).

2021-12-08 15:02 UTC, whereswaldon commented
I agree that until the relevant parts of `textlayout` are merged into go-text, depending on it is okay.I agree that until the relevant parts of `textlayout` are merged into go-text, depending on it is okay.

2021-12-08 15:04 UTC, andydotxyz commented
Why add this as a public dependency to the API usage when a simple alias would remove this requirement?
How things are implemented internally is a detail our users should not have to worry about.

2021-12-08 15:10 UTC, whereswaldon commented
Sure, we can use a type alias. I don't have strong opinions on that.

2021-12-08 15:29 UTC, benoitkugler commented
> Why add this as a public dependency to the API usage when a simple alias would remove this requirement?
> How things are implemented internally is a detail our users should not have to worry about.

I'm not sure to understand, do you mean an alias like `GlyphIndex = fonts.GID` ? That would still require adding the dependency right ?

Or do you mean changing the `fonts.GID` to a type alias ?

Note that with the code structure change discussed in https://github.com/go-text/shaping/issues/2#issuecomment-988891640, this dependency issue would not matter (for now) since `go-text/shaping` already depend on `textlayout`.

2021-12-08 17:47 UTC, whereswaldon commented
I could be wrong, but I believe that the strong objection was to having the `fonts` package symbol in the Public API, so introducing a type alias would address it.

2021-12-08 22:09 UTC, andydotxyz commented
That's right @whereswaldon - I think that our API should not expose internal implementation details.

> Note that with the code structure change discussed in go-text/shaping#2 (comment), this dependency issue would not matter (for now) since go-text/shaping already depend on textlayout.

This is correct, but an implementation detail should be part of a libraries public API in my opinion.

2021-12-09 14:13 UTC, whereswaldon approved these changes

2021-12-09 23:34 UTC, andydotxyz approved these changes

2021-12-10 00:02 UTC, stuartmscott approved these changes

2021-12-10 11:56 UTC, merged